auditforce/objects/Setup_Audit_Trail__c.object
<CustomObject>
    <fields>
        <fullName>Action_Short__c</fullName>
        <label>Action (Short)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Delegate_User__c</fullName>
        <label>Delegate User</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Setup_Audit_Trails</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Setup Audit Trail</label>
    <nameField>
        <displayFormat>Audit-{0}</displayFormat>
        <label>Setup Audit Trail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup Audit Trails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

auditforce/objects/TEMP_Setup_Audit_Trail__c.object
<CustomObject>
    <fields>
        <fullName>Action_Short__c</fullName>
        <label>Action (Short)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Delegate_User__c</fullName>
        <label>Delegate User</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TEMP_Setup_Audit_Trails</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>TEMP_Setup Audit Trail</label>
    <nameField>
        <displayFormat>TSAT-{0}</displayFormat>
        <label>TEMP_Setup Audit Trail  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TEMP_Setup Audit Trails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

auditforce/classes/AuditTrailBatchInsertToFinal.cls
global class AuditTrailBatchInsertToFinal implements Database.Batchable<sObject> {

	global Database.querylocator start(Database.BatchableContext BC) {
		String query =
		'SELECT Id, Date__c, Username__c, User__c, Action_Short__c, Action__c, Section__c, Delegate_User__c '+ 
		'FROM TEMP_Setup_Audit_Trail__c ORDER BY Date__c';
		return Database.getQueryLocator(query);
	}

	global void execute(Database.BatchableContext BC, List<sObject> scope){
		List<Setup_Audit_Trail__c> auditList = new List<Setup_Audit_Trail__c>();

		for(sObject s : scope){
			TEMP_Setup_Audit_Trail__c t = (TEMP_Setup_Audit_Trail__c)s;
			
			Setup_Audit_Trail__c a = new Setup_Audit_Trail__c(
			Date__c 			= t.Date__c, 
			Username__c			= t.Username__c, 
			User__c 			= t.User__c, 
			Action_Short__c 	= t.Action_Short__c,
			Action__c 			= t.Action__c, 
			Section__c			= t.Section__c, 
			Delegate_User__c 	= t.Delegate_User__c);

            auditList.add(a);
		}
		
		insert auditList;
	}	
	
	global void finish(Database.BatchableContext BC) {
		//TODO: nofify?	
	}	

}